name: fordev
description: A new Flutter project.
publish_to: 'none' 
scripts:
  build: flutter packages pub run build_runner build --delete-conflicting-outputs
  build_delete: flutter packages pub run build_runner build --delete-conflicting-outputs
version: 1.0.0+1
environment:
  sdk: ">=2.13.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  google_fonts: ^2.0.0
  provider: ^5.0.0
  equatable: ^2.0.0
  get: ^4.1.4
  flutter_secure_storage: ^4.2.0
  carousel_slider: ^4.0.0-nullsafety.0
  intl: ^0.17.0
  localstorage: ^4.0.0+1
dev_dependencies:
  faker: ^2.0.0-rc.2
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0
  # mocktail: ^0.1.4
flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/

flutter_icons: 
  ios: true
  android: true
  image_path_android: lib/ui/assets/icons/android.png
  image_path_ios: lib/ui/assets/icons/ios.png
  adaptive_cion_background: lib/ui/assets/icons/background.png
  adaptive_cion_foreground: lib/ui/assets/icons/foreground.png