name: fordev
description: A new Flutter project.
publish_to: 'none' 
scripts:
  build: flutter packages pub run build_runner build --delete-conflicting-outputs
  build_delete: flutter packages pub run build_runner build --delete-conflicting-outputs
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
dev_dependencies:
  faker: ^2.0.0-rc.2
  flutter_test:
    sdk: flutter
  mockito: ^5.0.7
  # mocktail: ^0.1.2
  # build_runner: ^1.10.0
  build_runner: 2.0.2
flutter:
  uses-material-design: true